[package]
name = "codecrafters-interpreter"
version = "0.1.0"
authors = ["Codecrafters <hello@codecrafters.io>"]
edition = "2021"
rust-version = "1.76"

[dependencies]
clap = { version = "4.5.17", features = ["derive"] }
